// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0-cRdxKHxRTOzm1TgZB1vubdpKU95KyM',
    appId: '1:239979151828:web:13139e058ca2073fd09641',
    messagingSenderId: '239979151828',
    projectId: 'apprize-e7156',
    authDomain: 'apprize-e7156.firebaseapp.com',
    storageBucket: 'apprize-e7156.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSEKqUpzD7-PZsdD_eJZHG4g5ZBSXZcjQ',
    appId: '1:239979151828:android:068d4e713bf7d87ed09641',
    messagingSenderId: '239979151828',
    projectId: 'apprize-e7156',
    storageBucket: 'apprize-e7156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgO3FBZ5BsNz16lpBqc5jS-PgIEHQaFEc',
    appId: '1:239979151828:ios:c31404ff3cc24d0ad09641',
    messagingSenderId: '239979151828',
    projectId: 'apprize-e7156',
    storageBucket: 'apprize-e7156.appspot.com',
    iosClientId: '239979151828-90uvhe3vrcj93qdsed0lskqpt92tmj0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.apprizeMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgO3FBZ5BsNz16lpBqc5jS-PgIEHQaFEc',
    appId: '1:239979151828:ios:c31404ff3cc24d0ad09641',
    messagingSenderId: '239979151828',
    projectId: 'apprize-e7156',
    storageBucket: 'apprize-e7156.appspot.com',
    iosClientId: '239979151828-90uvhe3vrcj93qdsed0lskqpt92tmj0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.apprizeMobileApp',
  );
}
